# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Projeto Helena
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright &copy; 2017 Anderson Antunes. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
highlighter: rouge
#permalink: pretty
permalink: /:categories/:year/:month/:day/:title

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/Tact-Tiles/
